### ISSUE TITLE
Run-time dependency wayfire found: NO

### ISSUE THREAD

**Issue by olignyf** [raspberrypi-ui/wf-panel-pi#10]
Hi,

I'm trying to build this on Raspberry Pi 5 and and I get stuck at this point:

`pi@pi5:~/wf-panel-pi $ meson setup builddir --prefix=/usr --libdir=/usr/lib/aarch64-linux-gnu
The Meson build system
Version: 1.0.1
Source dir: /home/pi/wf-panel-pi
Build dir: /home/pi/wf-panel-pi/builddir
Build type: native build
Project name: wf-panel-pi
Project version: 0.8.0
C compiler for the host machine: cc (gcc 12.2.0 "cc (Debian 12.2.0-14) 12.2.0")
C linker for the host machine: cc ld.bfd 2.40
C++ compiler for the host machine: c++ (gcc 12.2.0 "c++ (Debian 12.2.0-14) 12.2.0")
C++ linker for the host machine: c++ ld.bfd 2.40
Host machine cpu family: aarch64
Host machine cpu: aarch64
Found pkg-config: /usr/bin/pkg-config (1.8.1)
Found CMake: /usr/bin/cmake (3.25.1)
Run-time dependency wayfire found: NO (tried pkgconfig and cmake)

meson.build:16:0: ERROR: Dependency "wayfire" not found, tried pkgconfig and cmake
`

Any idea what I need to do to get wayfire?

Thanks!

**Comment by spl237** [comment]
sudo apt build-dep <name of package> automatically installs all the dependencies for a package, so in this case sudo apt build-dep wf-panel-pi.

**Comment by olignyf** [comment]
@spl237 If I have questions about upgrading my panel widget from Raspberry Pi 4 to Pi 5, where is the proper place to ask? Before I produced a .so file and added it to /usr/lib/aarch64-linux-gnu/lxpanel/plugins/. Now I don't know if additional libraries are supported? Thanks!

**Comment by spl237** [comment]
Unfortunately, the design of the Wayland panel application doesn't currently allow plugins to be dynamically loaded at run-time; they need to be statically built into the application itself. So you cannot at present have a plugin in an additional library.

I would very much like to be able to use dynamic loading for plugins, but it would be a pretty significant change to the panel code and would take me some time to implement. It is on the to-do list for the future, but I can't say when I am likely to be able to get around to do it - it is a fairly low priority for us at the moment.

**Comment by olignyf** [comment]
Hi, is the issue about not being able to create .so panel widget libraries still present? Should I open another ticket?
