### ISSUE TITLE
wf-panel-pi depends on 1.3.2-1+rpt12 which is not yet available

### ISSUE THREAD

**Issue by svenoix** [raspberrypi-ui/wf-panel-pi#11]
Hi,

(no sure if it is the right place to submit this issue)

I try to install wf-panel-pi but there is a dependency error:
>The following packages have unmet dependencies:
> wf-panel-pi : Depends: libfm-gtk4 (>= 1.3.2-1+rpt12) but 1.3.2-1+rpt11 is to be installed
>E: Unable to correct problems, you have held broken packages.

A look of [raspberry repo](https://archive.raspberrypi.com/debian/dists/bookworm/main/binary-amd64/Packages) confirms that wf-panel-pi depends on libfm-gtk4 >= 1.3.2-1+rpt12, but only version 1.3.2-1+rpt11 is available:

> Package: wf-panel-pi
> Version: 0.59
> Architecture: amd64
> Maintainer: Simon Long <simon@raspberrypi.com>
> Installed-Size: 2276
> Depends: libatk1.0-0 (>= 1.12.4), libatkmm-1.6-1v5 (>= 2.28.3), libc6 (>= 2.34), libcairo2 (>= 1.2.4), libdbusmenu-gtk3-4 (>= 0.4.2), **libfm-gtk4 (>= 1.3.2-1+rpt12)**, libfm4 (>= 0.1.99), libgcc-s1 (>= 3.0), libgdk-pixbuf-2.0-0 (>= 2.22.0), libglib2.0-0 (>= 2.74.0), libglibmm-2.4-1v5 (>= 2.66.5), libgtk-3-0 (>= 3.24), libgtk-layer-shell0 (>= 0.6.0), libgtkmm-3.0-1v5 (>= 3.24.7), libmenu-cache3 (>= 0.5.0), libnm0 (>= 1.24.0), libnma0 (>= 1.10.6-1+rpt1), libnotify4 (>= 0.7.0), libpackagekit-glib2-18 (>= 1.1.0), libpango-1.0-0 (>= 1.14.0), libpangocairo-1.0-0 (>= 1.14.0), libpangomm-1.4-1v5 (>= 2.46.3), libpulse0 (>= 0.99.1), libsecret-1-0 (>= 0.18), libsigc++-2.0-0v5 (>= 2.2.0), libstdc++6 (>= 11), libudev1 (>= 183), libwayland-client0 (>= 1.20.0), libwf-config1 (>= 0.7.1), wayfire, libfm-modules, eject, lxmenu-data, packagekit, raspi-config
> Recommends: pulseaudio, pipewire, pipewire-pulse, pi-bluetooth, pulseaudio-module-bluetooth, libspa-0.2-bluetooth, lp-connection-editor
> Homepage: <insert the upstream URL, if relevant>
> Priority: optional
> Section: unknown
> Filename: pool/main/w/wf-panel-pi/wf-panel-pi_0.59_amd64.deb
> Size: 437968
> SHA256: 17ae239d025c817a16d0f1922bdf67efd1c6329680a7b2d5a5629540f782f541
> SHA1: 98465e8648a3c852e32873376a424b05ba25c429
> MD5sum: ad84b7ed811609ddc43017e868f9c996
> Description: Raspberry Pi desktop panel for Wayfire
>  Raspberry Pi desktop panel based on wf-shell

and:

> Package: libfm-gtk4
> Source: libfm
> Version: **1.3.2-1+rpt11**
> Architecture: amd64
> Maintainer: Debian LXDE Maintainers <pkg-lxde-maintainers@lists.alioth.debian.org>
> Installed-Size: 489
> Depends: libatk1.0-0 (>= 1.12.4), libc6 (>= 2.29), libcairo2 (>= 1.10.0), libfm4 (= 1.3.2-1+rpt11), libgdk-pixbuf-2.0-0 (>= 2.22.0), libglib2.0-0 (>= 2.37.3), libgtk-3-0 (>= 3.21.5), libmenu-cache3 (>= 0.4.0), libpango-1.0-0 (>= 1.20.0), libfm-gtk-data (>= 1.2.0~)
> Recommends: eject
> Suggests: libfm-tools, nautilus-actions
> Multi-Arch: same
> Homepage: http://pcmanfm.sourceforge.net/
> Priority: optional
> Section: libs
> Filename: pool/main/libf/libfm/libfm-gtk4_1.3.2-1+rpt11_amd64.deb
> Size: 161460
> SHA256: 8aac8ce89ada2c871a93efeff3bc2d668ede982948737715998d6b0b6846e713
> SHA1: 5ba9e996eb8247524380c935ffca5838374f903f
> MD5sum: 838c067b357b6d6fc84172212594e46e
> Description: file management support (GTK+ 2.0 GUI library)
>  LibFM provides file management functions built on top of Glib/GIO
>  giving a convenient higher-level API.
>  .
>  This package contains the GTK+ version 2.0 GUI.

regards,
svx

**Comment by spl237** [comment]
This is being fixed at the moment - should be working in a couple of hours.
