### ISSUE TITLE
Possible incorrect filename in the power panel?

### ISSUE THREAD

**Issue by waveform80** [raspberrypi-ui/wf-panel-pi#12]
I'm currently in the process of making something vaguely similar to the power plugin, but for the Ubuntu desktop and noticed the following line in power.c is trying to open the `reset_event` node under the device-tree:

https://github.com/raspberrypi-ui/wf-panel-pi/blob/9b1b998064667f39b28edb035da9e5d1813e3084/src/panel/widgets/power/power.c#L91

However, this node doesn't exist on either the RaspiOS kernel or Ubuntu's variant (originally I thought maybe the name had changed across versions or something, but it doesn't appear on either). Would I be right in guessing this should be pointing at `<POWER_PATH>/power_reset` instead, or is `reset_event` a node that's only patched into the device-tree in certain circumstances?

**Comment by spl237** [comment]
This was tested and working before release, and I don't think any of the relevant kernel code has changed; my understanding is that the relevant file only exists when such a power event has actually occurred.

**Comment by waveform80** [comment]
I would humbly request someone at Pi towers double-check this. I've hooked up my Pi 5 to a bench supply and deliberately undervolted it to cause a reset. Under RaspiOS, after the reset there's no `reset_event` node, but `power_reset` does contain 2 (which is the expected value for an undervolt reset, looking at the code linked above).

Furthermore (presumably because it's looking for `reset_event` which doesn't exist), the desktop produced no warning about low power after the reboot ("Reset due to low power event"). It did warn about undervolt ("Low voltage warning") while I was lowering the voltage, so `low_voltage_thread` is working, but I'm reasonably sure at this point that `check_brownout` is looking at the wrong node.

**Comment by spl237** [comment]
Apologies - yes, you're quite right; it looks like this got changed at some point. I'll push out a fix today.

**Comment by timg236** [comment]
My bad .... @spl237 was given the wrong DT node name
