### ISSUE TITLE
Misleading text on netman applet menu

### ISSUE THREAD

**Issue by andrum993** [raspberrypi-ui/wf-panel-pi#17]
I use a wired network connection on all but one of my Raspberry Pi computers, and have the wireless interfaces disabled on these. Running the desktop, the netman applet on the panel shows me a greyed out menu item labelled `No network devices available`, even when that Pi is happily connected to the wired network using default settings, and the netman applet is indicating such. Can the text be changed to something more accurate, e.g. `No Wi-Fi(R) devices available` or `No wireless network devices available`?

**Comment by spl237** [comment]
Yes, that sounds sensible - I'll have a look at that.

**Comment by spl237** [comment]
Done - text is now "No wireless interfaces available". Not worth making a release just for this, but it will be included whenever we release the relevant packages next.
