### ISSUE TITLE
POTFILES.in needs update

### ISSUE THREAD

**Issue by Akkiesoft** [raspberrypi-ui/wf-panel-pi#2]
Hi.

I would like to update my Japanese translation.

However when I run the command to update Japanese po file, but I get the following error.

```
akkie@usbook:~/wf-panel-pi/po $ intltool-update ja
xgettext: error while opening "../src/panel/notify.c" for reading: No such file or directory
ERROR: xgettext failed to generate PO template file. Please consult
       error message above if there is any.
```

Indeed, src/panel/notify.c is not found. So I think POTFILES.in needs update.

I am currently updating POTFILES.in myself and updating the po file translation.

**Comment by spl237** [comment]
Sorry - yes, I need to update POTFILES.in; it's not been changed for a while. I'll have a look at it now.

**Comment by Akkiesoft** [comment]
Thank you.

I pulled latest commit. But I got another error.

Could you please check it again?

```
xgettext: error while opening "../src/panel/widgets/battery.cpp" for reading: No such file or directory
ERROR: xgettext failed to generate PO template file. Please consult
       error message above if there is any.
```

**Comment by spl237** [comment]
Sorry! Try it now...

**Comment by Akkiesoft** [comment]
Sorry, Next...

```
xgettext: "../src/panel/widgets/batt/batt-sys.c" for reading: No such file or directory
ERROR: xgettext failed to generate PO template file. Please consult
       error message above if there is any.
```

**Comment by Akkiesoft** [comment]
Next, "../src/panel/widgets/menu.cpp". Maybe smenu.cpp?

**Comment by spl237** [comment]
Sorry - have actually done what I should have done in the first place now and run intltool-update myself! Should be fine now.

**Comment by Akkiesoft** [comment]
Thank you very much! intltool-update can now complete.

I'll send a pull request to you when I've finished updating the translations :)
( There are a few areas that I am having trouble translating because I don't know how they work. I may ask you a question later. )
