### ISSUE TITLE
Menu icons broken

### ISSUE THREAD

**Issue by Botspot** [raspberrypi-ui/wf-panel-pi#21]
As of the apt update yesterday which included updates to the panel and wayland, I noticed a regression in the start menu.

![20241029_14h13m00s_grim](https://github.com/user-attachments/assets/1b6d25e6-052f-4450-8ee1-1a502c60f339)

The update seems to have broken much of the versatility in how icons are specified in .desktop files.

Here's some examples of the `Icon=` lines in affected menu entries on my system:

- Icon=netsurf.png
- Icon=/home/pi/pi-apps/icons/logo.png
- Icon=circuslinux-icon.xpm
- Icon=/home/pi/cool-retro-term/app/icons/64x64/cool-retro-term.png
- Icon=/usr/share/tilp2/pixmaps/tilp.png
- Icon=/home/pi/.local/share/waydroid/data/icons/com.android.contacts.png

I believe this commit caused the regression.
https://github.com/raspberrypi-ui/wf-panel-pi/commit/efafe5800adbf76869c8b7f1e03b6cf6dd4d4622

**Comment by spl237** [comment]
Icons now have to be specified as being in the icon theme rather than directly loaded as file paths. This is to avoid situations where an incorrect fallback icon was being loaded instead of the correct one due to anomalies in how the file manager icon loading code worked.

If I get a chance, I may look at allowing complete file paths to be used, which would fix some of your problems, but I don't think specifying file names without paths is ever going to be supported.

**Comment by Botspot** [comment]
Same issue reported on the Pi forums. https://forums.raspberrypi.com/viewtopic.php?t=378537

> but I don't think specifying file names without paths is ever going to be supported.

In that case, it would seem that at least the Netsurf browser deb package on the official Pi repos needs a patch now.

- Icon=netsurf.png

**Comment by spl237** [comment]
We haven't supported netsurf for years...

**Comment by Botspot** [comment]
For what it's worth, this does break the freedesktop spec.
https://specifications.freedesktop.org/desktop-entry-spec/latest/recognized-keys.html
![20241029_14h35m44s_grim](https://github.com/user-attachments/assets/96dc3a1d-92b2-47cb-9ac0-d8608431368d)

**Comment by spl237** [comment]
The previous implementation also broke the freedesktop icon search spec by using a very perverse algorithm to find fallbacks! Just depends on which form of brokenness you personally find preferable... ;)

I'll reinstate full path lookup when I get a chance. Shouldn't be too difficult.

**Comment by Botspot** [comment]
> I'll reinstate full path lookup when I get a chance. Shouldn't be too difficult.

Thank you.

When I get a chance to, I will check how commonly debian packages specify non-full-path exact filenames, in the way that Netsurf does. If the number of affected packages is more than a few, would such findings change your mind on the matter and encourage you to look for a way to restore full functionality?

**Comment by spl237** [comment]
I've just added full path support - it will be in the next release.

Specifying file names without paths does not appear to be supported at all by the FreeDesktop spec anyway; there is AFAIK no standard location in which to look for them. My guess is that they were previously handled by ignoring the extension and looking the name up in the icon theme - I've got no real interest in adding that.

I think full path support and icon theme lookup is sufficient. Anything else is just confusing...

**Comment by archisman-panigrahi** [comment]
It seems that while it is fixed for menu icons, when I pin them to panel, the issue remains - desktop files with hardcoded full icon path (not in /usr/share/icons) don't show up when pinned to the panel. It just creates an empty space on the panel, clicking on which, the app opens.

Should I create a new issue?

**Comment by spl237** [comment]
> It seems that while it is fixed for menu icons, when I pin them to panel, the issue remains - desktop files with hardcoded full icon path (not in /usr/share/icons) don't show up when pinned to the panel. It just creates an empty space on the panel, clicking on which, the app opens.
> 
> Should I create a new issue?

Yes, please do - that is a completely different piece of code, and the problem will require a different fix.
