### ISSUE TITLE
140 debian applications broken by menu update

### ISSUE THREAD

**Issue by Botspot** [raspberrypi-ui/wf-panel-pi#22]
This issue is based on the previous issue here: https://github.com/raspberrypi-ui/wf-panel-pi/issues/21

While the detection of explicit icons paths was restored in commit https://github.com/raspberrypi-ui/wf-panel-pi/commit/d7694198be1ee77dcac8b0373771c43decc221af, the menu will still fail to detect a suitable icon for .desktop files that specify an explicit filename without a full path.

This may seem like an edge case. The functionality is not guaranteed in the Freedesktop spec, and I agree with you that it seems like an ugly hack. In fact I only even noticed it thanks to Netsurf web browser. To check if this was unique to Netsurf or if it affected other applications, I wrote a script to download every apt package containing a .desktop file and check for the presence of this specific icon reference style.
Here is the script.
```bash
#!/bin/bash
#dependencies
sudo apt install -yf apt-file
mkdir ~/desktop-files
IFS=$'\n'
cd "$(mktemp -d)"
apps="$(apt-file search /usr/share/applications | awk -F ': ' '{print $1}' | uniq)"

for app in $apps;do
  rm -rf extracted *.deb
  apt download $app
  mkdir extracted
  dpkg-deb -x *.deb extracted
  cat extracted/usr/share/applications/* > ~/desktop-files/$app.txt
  
done
rm -rf extracted *.deb
cd ~/desktop-files
grep '^Icon=' -r | sort -u | sed 's/\.txt//g ; s/:I/: I/g ; s/^/- /g' | grep '\.' | grep -v '/\|\..*\.\|\..*: \|\..$\|application-vnd\.iccprofile'
```
This was the output.
- alien-arena: Icon=alien-arena.png
- asciijump: Icon=asciijump.xpm
- biglybt: Icon=biglybt.svg
- bitmeter: Icon=bitmeter.xpm
- black-box: Icon=black-box.png
- boats: Icon=boats.png
- circuslinux: Icon=circuslinux-icon.xpm
- clips: Icon=clips.xpm
- crack-attack: Icon=crack-attack.xpm
- cytadela: Icon=cytadela.png
- deb-gview: Icon=deb-gview.xpm
- devede: Icon=devedeng_icon.svg
- dfcgen-gtk: Icon=dfcgen-gtk.png
- dhewm3-d3xp: Icon=doom3.png
- dhewm3-doom3: Icon=doom3.png
- direwolf: Icon=direwolf_icon.png
- efax-gtk: Icon=efax-gtk.png
- einstein: Icon=einstein.png
- euler: Icon=euler-32.xpm
- expeyes: Icon=expeyes-junior-icon.png
- expeyes: Icon=nuclear-icon.png
- eyes17: Icon=eyes17-logo.png
- fbreader: Icon=FBReader.png
- filler: Icon=filler.png
- fluidsynth-dssi: Icon=fluidsynth-dssi.xpm
- formiko: Icon=formiko.png
- free42-nologo: Icon=free42.xpm
- gbatnav: Icon=gnome-gbatnavd.png
- gbatnav: Icon=gnome-gbatnav.png
- gconjugue: Icon=gconjugue.png
- gdmap: Icon=gdmap_icon.png
- gemdropx: Icon=gemdropx-icon.xpm
- gfpoken: Icon=gfpoken.png
- gfsview: Icon=application-gerris.png
- gftp-gtk: Icon=gftp.png
- ggobi: Icon=ggobi.png
- ginga: Icon=ginga.svg
- gjiten: Icon=jiten.png
- glurp: Icon=glurp.svg
- gmanedit: Icon=gmanedit_icon.png
- gnome-breakout: Icon=gnome-breakout.png
- gnome-paint: Icon=gp.png
- goattracker: Icon=goattrk2.xpm
- golly: Icon=golly.xpm
- gopchop: Icon=gopchop.png
- granule: Icon=granule.png
- grsync: Icon=grsync.png
- gtetrinet: Icon=gtetrinet.png
- gtkterm: Icon=gtkterm.png
- guidedog: Icon=guidedog.png
- guymager: Icon=guymager_128.png
- gvb: Icon=gvb.svg
- hannah: Icon=hannah.xpm
- hasciicam: Icon=hasciicam.png
- hoteldruid: Icon=hoteldruid.png
- httraqt: Icon=httraqt.xpm
- iraf: Icon=iraf.svg
- jamin: Icon=jamin.svg
- jftp: Icon=jftp.xpm
- jmeter: Icon=jmeter.png
- juce-tools: Icon=juce.png
- jverein: Icon=jverein-icon.png
- kcheckers: Icon=biglogo.png
- kluppe: Icon=kluppe.png
- klystrack: Icon=klystrack.png
- kylin-scanner: Icon=scanner.png
- matchbox-panel-manager: Icon=mbpanelmgr.png
- matchbox-panel: Icon=mbmenu.png
- matchbox-panel: Icon=miniapm.png
- matchbox-panel: Icon=minisys.png
- matchbox-panel: Icon=minitime.png
- matchbox-panel: Icon=signal-81-100.png
- medcon: Icon=xmedcon.xpm                                                                                                                                                                           
- meterbridge: Icon=meterbridge32x32.xpm
- microhope: Icon=gnome-word.png
- microhope: Icon=mh-logo.png
- milkytracker: Icon=milkytracker.png
- mnemosyne: Icon=mnemosyne.png
- monodoc-http: Icon=monodoc.png
- netmate: Icon=netmate.xpm
- netsurf-gtk: Icon=netsurf.png
- neurodebian-desktop: Icon=3DSlicerLogo-DesktopIcon-48x48x256.png
- neurodebian-desktop: Icon=fslview.xpm
- neurodebian-desktop: Icon=itksnap.xpm
- neurodebian-desktop: Icon=mricron.xpm
- neurodebian-desktop: Icon=mrtrix.xpm
- neurodebian-desktop: Icon=openelectrophy.png
- neurodebian-desktop: Icon=sigviewer128.png
- neurodebian-desktop: Icon=spykeviewer.png
- nted: Icon=nted.png
- oce-draw: Icon=occ-icon-32.xpm
- odin: Icon=odin.png
- openmotor: Icon=oMIconCycles.png
- openuniverse: Icon=openuniverse.xpm
- orbital-eunuchs-sniper: Icon=orbital-eunuchs-sniper.png
- pacman4console: Icon=pacman4console.xpm
- pampi: Icon=pampi_icon.png
- pinball: Icon=pinball.xpm
- proofgeneral: Icon=proofgeneral.png
- psk31lx: Icon=psk31lx.png
- pyacidobasic: Icon=pyacidobasic.svg
- pycode-browser: Icon=gnome-word.png
- python3-guidata: Icon=guidata.svg
- python3-navarp: Icon=navarp.svg
- python3-whiteboard: Icon=pywb_pixmap.xpm
- qml-module-qtmir: Icon=xwayland.qtmir
- qtscrob: Icon=qtscrob.png
- quarry: Icon=quarry.png
- rasterview: Icon=rasterview.png
- rxvt-unicode: Icon=urxvt_48x48.xpm
- saods9: Icon=SAOImageDS9.svg
- sigviewer: Icon=sigviewer128.png
- simple-image-reducer: Icon=simple-image-reducer.png
- songwrite: Icon=songwrite3.png
- sopwith: Icon=sopwith.png
- spread-phy: Icon=sofa.png
- spview: Icon=org.spview
- streamtuner2: Icon=streamtuner2.png
- structure-synth: Icon=structure-synth.png
- sweep: Icon=sweep.svg
- telegnome: Icon=telegnome.png
- trustedqsl: Icon=trustedqsl.png
- twclock: Icon=twclock.png
- twpsk: Icon=twpsk.png
- uhexen2: Icon=hexen2.png
- virtualjaguar: Icon=vj.xpm
- vodovod: Icon=vodovod.xpm
- wifi-qr: Icon=wifi-qr.svg
- wmgui: Icon=wmgui.xpm
- xcfa: Icon=xcfa.png
- xjump: Icon=xjump-icon.xpm
- xlog: Icon=xlog-icon.png
- xmoto: Icon=xmoto.xpm
- xterm: Icon=mini.xterm
- xtrkcad: Icon=xtrkcad.png
- xygrib: Icon=xygrib.png
- xyscan: Icon=xyscanIcon.png
- yasw: Icon=application.png
- zulucrypt-gui: Icon=zuluCrypt.xpm
- zulumount-gui: Icon=zuluMount.xpm

It found 140 affected packages out of the 2791 total packages that have a menu launcher, meaning that this update to the menu breaks the icon for about 5% of all GUI applications, or 1 in 20.

This is far more significant than I had expected. I had predicted the number of affected apps would be well under 1%.

With these findings in mind, I can think of a few solutions:

1. Patch every affected package upstream to have them use full paths or remove the file extension. (unrealistic)
2. Patch the menu to ignore the file extension and search for the icon in the icon theme.
3. Implement a simple search algorithm for at least /usr/share/pixmaps and /usr/share/icons to look for the filename.
4. Restore the libfm searching algorithm, but only use it if a file extension is detected. (partially restoring functionality that was removed in commit https://github.com/raspberrypi-ui/wf-panel-pi/commit/efafe5800adbf76869c8b7f1e03b6cf6dd4d4622)
5. Do nothing and [still claim](https://github.com/raspberrypi-ui/wf-panel-pi/issues/21#issuecomment-2445217661) it is not worth fixing. I would hope that you choose not to do this.

**Comment by spl237** [comment]
> 5. Do nothing and [still claim](https://github.com/raspberrypi-ui/wf-panel-pi/issues/21#issuecomment-2445217661) it is not worth fixing. I would hope that you choose not to do this.

I'm afraid that is exactly what I am going to do. As far as I can tell, the use of an explicit icon file name without a path is not supported by the FreeDesktop spec, so these applications do not conform to it - I suspect most of them are rather old and unmaintained. I also suspect that on various other distros, they would also get no icon loading, because the handling of anything other than a fully-specified path is down to the implementation, and any fix for this is going to involve an ugly hack which is not supported by the spec.

Most people will never install any of these applications on Pi (or, by the look of most of them, any other distro...) so I feel that this very much is an edge case that will affect a very small number of icons on the system for a very small number of users. If that turns out not to be the case in reality, I can revisit this, but for now, we will be following the FreeDesktop spec and supporting full paths and icon lookup in the theme only.

**Comment by spl237** [comment]
On reading the FreeDesktop spec again, it seems that installing icon files in /usr/share/pixmaps is (or at least used to be) legitimate, and in the case of Netsurf, that is the only place it puts an icon file anyway.

So I am going to add a fallback option so that if an explicit path is not specified and the named icon is not found in the theme, then I will look for that named icon in /usr/share/pixmaps. I suspect this will fix the vast majority of the cases above, which look like old and unmaintained apps which may have used this earlier location for icon installation.
