### ISSUE TITLE
Icons pinned to panel are broken for full paths and filenames specified in .desktop files

### ISSUE THREAD

**Issue by archisman-panigrahi** [raspberrypi-ui/wf-panel-pi#24]
Desktop files with hardcoded full icon path don't show any icons when pinned to the panel. 
It just creates an empty space on the panel, clicking on which, the app opens.

Previously the icons did not show up in the menu either, but that has been fixed recently https://github.com/raspberrypi-ui/wf-panel-pi/issues/21.

To reproduce:

1. Create a desktop file with hardcoded icon path. Let's suppose the icon is in the home folder. Save the .desktop file in `.local/share/applications` and mark it as executable.
2. The desktop file shows up in the menu with its correct icon. Right click on it, and pin to launcher on the panel
3. In the panel, an empty space for launcher is produced, without any icon. Clicking on that empty space opens the app.

**Comment by spl237** [comment]
Now fixed.

**Comment by archisman-panigrahi** [comment]
I verify that it is fixed. Thank you.
