### ISSUE TITLE
Some texts are not applied to the translated text

### ISSUE THREAD

**Issue by Akkiesoft** [raspberrypi-ui/wf-panel-pi#3]
For several reasons, translated text does not seem to be reflected in the UI.

1. Translated text for "src/panel/panel.cpp" is not reflected in the UI. (Sorry I don't know why...)
2. Some resources written in .hpp file. But hpp files does not included in POTFILES.in.

**Comment by spl237** [comment]
2. OK, have found all of these - they are the configuration parameter names. I'll upload a new POTFILES in a bit...

**Comment by spl237** [comment]
New POTFILES.in is updated.

I'll have a look at panel.cpp.

**Comment by spl237** [comment]
Try it now - I *think* that should have fixed it, but let me know if not!

**Comment by spl237** [comment]
Brilliant - thanks for confirming! (And sorry for not getting it right in the first place - I should have checked that translations were working before launch, but ran out of time...)
