### ISSUE TITLE
Excessive memory consumption

### ISSUE THREAD

**Issue by JinShil** [raspberrypi-ui/wf-panel-pi#4]
wf-panel-pi appears to consume a disproportionate amount of memory for the service it provides:

![image](https://github.com/raspberrypi-ui/wf-panel-pi/assets/6023641/809d7cef-0b65-4103-8dae-78e728ded33b)

Is there potential for a significant reduction in memory consumption with some optimiziation?

**Comment by spl237** [comment]
Given the amount of functionality the panel and its plugins offer, 3.5% of memory is not that unreasonable.

If it is leaking memory - if that 3.5% increases over time - then I can investigate that, but if that 3.5% is static, then there's not much that can be done. You could try removing some of the plugins which you don't use to see if that helps.

**Comment by spl237** [comment]
Please report back if it is indeed leaking, but otherwise closing.

**Comment by Wizard37** [comment]
Hi, reporting back -- my pi was idle for a while and checking top from terminal, wf-panel-pi (latest as of today) was using 771MB RAM. I logged out and logged back in and it's using 72MB. Going to leave it idle so that I can report the memory usage increasing. Are there any logs or diagnostic information I can provide to help isolate this issue?

**Comment by brightyu777** [comment]
I am wondering if there is a memory leak error. I am running this on raspberry pi desktop (Bookworm) and sometimes see the memory usage has gone up a lot. Running on a Raspberry Pi 4 (1 GB version).
It doesn't always do this and most of the time it is lower memory usage. 

<img width="1147" height="680" alt="Image" src="https://github.com/user-attachments/assets/c0f6f4d9-33a4-4626-aa08-95359638c724" />

**Comment by spl237** [comment]
Plugins are now built as dynamically-loaded code, so it would help if you can work out under what circumstances you see this high usage, and repeat them removing the plugins one at a time to narrow down which might be causing it.

In case it helps, this week I found several memory leaks in the device ejecter plugin which are now fixed, but you may still have the old version - if you were doing a lot of connecting and disconnecting external drives, memory would have leaked then.
