### ISSUE TITLE
Questions about some setting items

### ISSUE THREAD

**Issue by Akkiesoft** [raspberrypi-ui/wf-panel-pi#5]
Hi.

I have a question about what effect some settings have.
Because I want to understand them before I translate them.

I apologize if this is already documented somewhere.
It would be helpful if you could let me know where the documentation is.

## Start menu configuration

In start menu configuration, we can configure about search window. but I can not found search window.
What is search window?
When I open start menu and type something, I can search items within the menu but I seem it's not search window.

https://github.com/raspberrypi-ui/wf-panel-pi/assets/422590/bbb97684-0ea0-442f-8c50-790400042ff7

## System tray configuration

There are two items in the system tray settings:  "Smooth scrolling threshold" and "Middle button activate menu".

<img width="876" alt="system-tray-configuration" src="https://github.com/raspberrypi-ui/wf-panel-pi/assets/422590/d89118d9-1eef-4839-ae7e-fd366054633c">

I couldn't understand how the settings worked.

Is this the correct location for the taskbar plugin?

<img width="1277" alt="panel" src="https://github.com/raspberrypi-ui/wf-panel-pi/assets/422590/fb36c132-66f2-4420-a7da-5a2d8fcc9fcd">

**Comment by spl237** [comment]
On the search menu - yes, that window you have shown in the video is the search window. You can set that window to always be the same height, or to grow and shrink depending on how many results are found. The height setting is either the maximum height of the window, or the height it always has if it is set to always be the same height.

The system tray - the middle button activates menu option changes whether the middle or right mouse button activates the menu - by default it is the right; if you turn that on it is the middle.

I have to admit I have never worked out what the smooth scrolling threshold is! That is one of the plugins I didn't write myself, so don't fully understand it.

And yes, that is the usal location for the window list plugin.

**Comment by Akkiesoft** [comment]
Thank you for your reply.

Search menu:
I understand it. I have confirmed that how it works.

System tray:
Sorry I am confused.
The red frame is the window list, not the system tray, right?
I tried moving the system tray to different locations several times and I found that it wasn't visible to me.
How can i see it...?

<img width="610" alt="system-tray" src="https://github.com/raspberrypi-ui/wf-panel-pi/assets/422590/a51bbb35-7680-426a-8e26-f332c82fdb41">

Thanks.

**Comment by Akkiesoft** [comment]
I still have the above question, but I will complete the translation and send it to you later.

**Comment by spl237** [comment]
Ah - sorry; I misunderstood. The system tray is an area for other applications to display icons - it is only visible if applications are running which put icons into it. Try running VLC - the system tray will then show the VLC icon.

**Comment by Akkiesoft** [comment]
Thank you, I was able to confirm.

I can also put the fcitx-mozc into System Tray, very impressive.
And I remembered. I see that the system tray I asked you about in the forum before is now supported. Thank you very much! :)
