### ISSUE TITLE
Power supply redirect url appears to be incorrect.

### ISSUE THREAD

**Issue by steev** [raspberrypi-ui/wf-panel-pi#7]
In https://github.com/raspberrypi-ui/wf-panel-pi/blob/378520b7aa2e43bf5c6ace4148b8bb47e77fef99/src/panel/widgets/power/power.c#L241 the redirect url was changed, however it appears the original https://rptl.io/rp5-power_supply link takes you properly to https://www.raspberrypi.com/documentation/computers/raspberry-pi-5.html#powering-raspberry-pi-5 whereas the current one https://rptl.io/rp5-power-supply-info takes me to https://www.raspberrypi.com/

**Comment by spl237** [comment]
Now fixed - many thanks!
