### ISSUE TITLE
Battery widget doesn't show on a Raspberry Pi

### ISSUE THREAD

**Issue by ngreatorex** [raspberrypi-ui/wf-panel-pi#8]
Due to the below lines, the battery widget will never find a battery when it's running on a Pi.

https://github.com/raspberrypi-ui/wf-panel-pi/blob/34c974e22f90245a541aad9c19ddf80aabc263a5/src/panel/widgets/batt/batt.c#L371-L374

Is this intended behaviour or an accidental use of `#ifndef` instead of `#ifdef`?

In my case, I'm using a Raspberry Pi CM4 in a battery powered device and it would be useful to be able to monitor the battery state from the panel.

**Comment by spl237** [comment]
It's deliberate. The battery plugin is only intended for use on laptops running the forthcoming X86 version of the OS, as they support a standard mechanism for accessing the battery state. Monitoring the state of a battery-powered Pi device would require custom software to access battery info.

**Comment by ghollingworth** [comment]
Have you tested the code with the device enabled?

We do not have any battery monitoring on the Raspberry Pi (or support a HAT with such a battery monitor), as such we can't test whether it works or not.

You would have to:
1) Enable it locally, rebuild it and test it works correctly
2) Check that nothing else is broken by enabling it
3) Test it for future releases of the plugin
4) Maintain its functionality for any changes to the Linux kernel /sys/class/battery (Doubt there should be many here!)

**Comment by ngreatorex** [comment]
Thanks for the prompt responses. I have tried removing the `#ifndef` (and corresponding `#endif`) and run it on my CM4 (with battery) and Pi 5 (without). The battery icon then shows up on the CM4 and nothing changes on the Pi 5 desktop. The only difference I can see is that the Pi 5 now outputs e.g. `** Message: 19:25:26.985: ptbatt: battery 0 not found` on stderr when running from the command line (I'm not sure if that stderr output is captured anywhere when run automatically from Wayfire).

Unfortunately, I cannot currently commit to testing and maintaining the functionality going forward. For now I will continue with my locally patched version and hope someone is able to take on the maintenance of this in the future.

**Comment by spl237** [comment]
OK, thanks for testing - we'll look at enabling the functionality by default.
